# Lista de Exercícios: NumPy com Dataset do Spotify

Considere a seguir a leitura e carregamento do dataset em um ndarray chamado `dados`.

In [1]:
import kagglehub

# Baixando a última versão no kaggle
path = kagglehub.dataset_download("maharshipandya/-spotify-tracks-dataset")

print("Path to dataset files:", path)



Extracting files...
Path to dataset files: C:\Users\leois\.cache\kagglehub\datasets\maharshipandya\-spotify-tracks-dataset\versions\1


100%|##########| 8.17M/8.17M [00:02<00:00, 3.49MB/s]


In [2]:
#leitura do arquivo

import numpy as np
dados_numericos = []
with open(path+"/dataset.csv", "r", encoding="utf-8") as arquivo:
    linhas = arquivo.readlines() # lê todas as linhas
    linhas = linhas[1:] # remove cabeçalho
    for linha in linhas:
        try:
            linha = linha.strip() # remove quebra de linha
            colunas = linha.split(",") # separa colunas
            # pega apenas colunas numéricas ( popularity, duration_ms, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness liveness, valence, tempo, time_signature)
            valores = [
                float(colunas[5]), float(colunas[6]), float(colunas[8]), float(colunas[9]), float(colunas[10]), float(colunas[11]), float(colunas[12]), float(colunas[13]), float(colunas[14]), float(colunas[15]), float(colunas[16]), float(colunas[17]), float(colunas[18]), float(colunas[19])
            ]
            dados_numericos.append(valores)
        except:
            pass
dados = np.array(dados_numericos) # converte para ndarray

print(dados.shape)

print(dados.dtype)

np.set_printoptions(suppress=True)
print(dados)

(106882, 14)
float64
[[    73.    230666.         0.676 ...      0.715     87.917      4.   ]
 [    55.    149610.         0.42  ...      0.267     77.489      4.   ]
 [    57.    210826.         0.438 ...      0.12      76.332      4.   ]
 ...
 [    22.    271466.         0.629 ...      0.743    132.378      4.   ]
 [    41.    283893.         0.587 ...      0.413    135.96       4.   ]
 [    22.    241826.         0.526 ...      0.708     79.198      4.   ]]


#1) Estatísticas da Energia
* Selecione a coluna `energy`.
* Calcule média, desvio padrão, maior valor e menor valor.

In [3]:
# Coluna energy está no índice 3 (col[9] do CSV original)
energy = dados[:, 3]

media       = np.mean(energy)
desvio_pad  = np.std(energy)
maior_valor = np.max(energy)
menor_valor = np.min(energy)

print("=== Estatísticas da Coluna Energy ===")
print(f"  Média:          {media:.4f}")
print(f"  Desvio padrão:  {desvio_pad:.4f}")
print(f"  Maior valor:    {maior_valor:.4f}")
print(f"  Menor valor:    {menor_valor:.4f}")

=== Estatísticas da Coluna Energy ===
  Média:          0.6492
  Desvio padrão:  0.2457
  Maior valor:    1.0000
  Menor valor:    0.0000


#2) Filtro de Músicas Energéticas
Selecione músicas com `energy > 0.8` e `danceability > 0.7`.

In [4]:
# danceability = índice 2 | energy = índice 3
mascara = (dados[:, 3] > 0.8) & (dados[:, 2] > 0.7)
musicas_energeticas = dados[mascara]

print("=== Músicas com energy > 0.8 e danceability > 0.7 ===")
print(f"  Total de músicas filtradas: {musicas_energeticas.shape[0]}")
print(f"  Percentual do dataset:      {musicas_energeticas.shape[0] / dados.shape[0] * 100:.2f}%")
print(f"\n  Primeiras 5 linhas (popularity, duration_ms, danceability, energy ...):")
print(musicas_energeticas[:5, :4])

=== Músicas com energy > 0.8 e danceability > 0.7 ===
  Total de músicas filtradas: 6743
  Percentual do dataset:      6.31%

  Primeiras 5 linhas (popularity, duration_ms, danceability, energy ...):
[[    62.    229320.         0.709      0.913]
 [    32.    233280.         0.732      0.83 ]
 [    28.    243840.         0.719      0.849]
 [    27.    177666.         0.731      0.868]
 [    26.     73501.         0.712      0.933]]


#3) Normalização Vetorial
Normalize cada linha utilizando norma vetorial unitária.

In [5]:
# Norma L2 de cada linha (keepdims mantém shape (N,1) para broadcast)
normas = np.linalg.norm(dados, axis=1, keepdims=True)

# Evita divisão por zero
normas[normas == 0] = 1

dados_norm_linhas = dados / normas

print("=== Normalização Vetorial por Linha (norma L2) ===")
print(f"  Shape resultado:  {dados_norm_linhas.shape}")
print(f"  Norma da linha 0 (deve ser ≈ 1.0): {np.linalg.norm(dados_norm_linhas[0]):.6f}")
print(f"  Norma da linha 1 (deve ser ≈ 1.0): {np.linalg.norm(dados_norm_linhas[1]):.6f}")
print("\n  Primeiras 3 linhas normalizadas:")
print(dados_norm_linhas[:3])

=== Normalização Vetorial por Linha (norma L2) ===
  Shape resultado:  (106882, 14)
  Norma da linha 0 (deve ser ≈ 1.0): 1.000000
  Norma da linha 1 (deve ser ≈ 1.0): 1.000000

  Primeiras 3 linhas normalizadas:
[[ 0.00031647  0.99999988  0.00000293  0.000002    0.00000434 -0.00002925
   0.          0.00000062  0.00000014  0.          0.00000155  0.0000031
   0.00038114  0.00001734]
 [ 0.00036762  0.99999979  0.00000281  0.00000111  0.00000668 -0.0001152
   0.00000668  0.00000051  0.00000618  0.          0.00000068  0.00000178
   0.00051794  0.00002674]
 [ 0.00027037  0.9999999   0.00000208  0.0000017   0.         -0.00004617
   0.00000474  0.00000026  0.000001    0.          0.00000055  0.00000057
   0.00036206  0.00001897]]


#4) Similaridade entre Features

Normalize as colunas e calcule `dados_norm.T @ dados_norm`.

In [6]:
# Normalização por coluna (Min-Max para escala [0,1])
col_min = dados.min(axis=0)
col_max = dados.max(axis=0)
col_range = col_max - col_min
col_range[col_range == 0] = 1  # evita divisão por zero

dados_norm = (dados - col_min) / col_range

# Produto matricial: matriz de similaridade (14 x 14)
similaridade = dados_norm.T @ dados_norm

print("=== Matriz de Similaridade entre Features (14 x 14) ===")
print(f"  Shape: {similaridade.shape}")
print("\n  Matriz:")
np.set_printoptions(suppress=True, precision=1, linewidth=120)
print(similaridade)

=== Matriz de Similaridade entre Features (14 x 14) ===
  Shape: (14, 14)

  Matriz:
[[17358.8  1560.9 20836.4 23123.6 17305.6 27545.9 22591.1  3026.8 10928.2  4840.8  7281.2 16782.9 18056.7 28090.2]
 [ 1560.9   246.1  2668.9  3055.2  2261.2  3573.3  2921.2   395.1  1349.1   788.    956.1  2139.   2351.2  3646.1]
 [20836.4  2668.9 39027.2 40629.9 30127.  47813.2 38602.8  5655.8 17973.5  8337.3 12174.  31768.9 30953.5 48657.6]
 [23123.6  3055.2 40629.9 51502.9 33950.7 54980.4 43071.3  6510.2 14935.9  9182.2 15088.8 34809.2 35680.4 54640.4]
 [17305.6  2261.2 30127.  33950.7 36200.6 39767.  30533.3  4619.5 15325.3  7707.  10539.  24980.1 26057.9 40454.4]
 [27545.9  3573.3 47813.2 54980.4 39767.  63726.7 51844.4  7276.1 23214.1 11141.9 16891.9 39774.  41481.8 64237.2]
 [22591.1  2921.2 38602.8 43071.3 30533.3 51844.4 67820.   5716.2 22250.   9369.2 13994.2 32625.  34123.6 52904.4]
 [ 3026.8   395.1  5655.8  6510.2  4619.5  7276.1  5716.2  2098.   2884.5  1115.8  2375.1  4593.3  4755.9  735

#5) Classificação com np.where

Crie um array chamado `categoria` usando `np.where`.
Se popularidade >= 80 "Hit", senão "Normal".

In [7]:
# popularity = índice 0
popularidade = dados[:, 0]

categoria = np.where(popularidade >= 80, "Hit", "Normal")

total_hits   = np.sum(categoria == "Hit")
total_normal = np.sum(categoria == "Normal")

print("=== Classificação por Popularidade ===")
print(f"  Total de músicas:  {len(categoria)}")
print(f"  Hits (>= 80):      {total_hits}  ({total_hits/len(categoria)*100:.2f}%)")
print(f"  Normais (< 80):    {total_normal}  ({total_normal/len(categoria)*100:.2f}%)")
print(f"\n  Primeiros 10 valores de 'categoria':")
print(categoria[:10])
print(f"  Popularidades correspondentes:")
print(popularidade[:10].astype(int))

=== Classificação por Popularidade ===
  Total de músicas:  106882
  Hits (>= 80):      1169  (1.09%)
  Normais (< 80):    105713  (98.91%)

  Primeiros 10 valores de 'categoria':
['Normal' 'Normal' 'Normal' 'Normal' 'Hit' 'Normal' 'Normal' 'Hit' 'Normal' 'Normal']
  Popularidades correspondentes:
[73 55 57 71 82 58 74 80 74 56]


#6) Ordenação por Popularidade

Ordene as músicas pela coluna popularity.

In [8]:
# argsort retorna os índices que ordenariam o array
# [::-1] inverte para ordem decrescente (mais populares primeiro)
indices_ordenados = np.argsort(dados[:, 0])[::-1]
dados_ordenados = dados[indices_ordenados]

np.set_printoptions(suppress=True, precision=3)

print("=== Dataset Ordenado por Popularidade (decrescente) ===")
print(f"  Shape: {dados_ordenados.shape}")
print("\n  Top 5 músicas mais populares (todas as 14 features):")
print(dados_ordenados[:5])

print("\n  5 músicas menos populares:")
print(dados_ordenados[-5:])

print(f"\n  Popularidade máxima: {dados_ordenados[0, 0]:.0f}")
print(f"  Popularidade mínima: {dados_ordenados[-1, 0]:.0f}")

=== Dataset Ordenado por Popularidade (decrescente) ===
  Shape: (106882, 14)

  Top 5 músicas mais populares (todas as 14 features):
[[   100.    156943.         0.714      0.472      2.        -7.375      1.         0.086      0.013      0.
       0.266      0.238    131.121      4.   ]
 [   100.    156943.         0.714      0.472      2.        -7.375      1.         0.086      0.013      0.
       0.266      0.238    131.121      4.   ]
 [    98.    162637.         0.835      0.679      7.        -5.329      0.         0.036      0.583      0.
       0.218      0.85     124.98       4.   ]
 [    98.    175238.         0.561      0.965      7.        -3.673      0.         0.034      0.004      0.
       0.371      0.304    128.04       4.   ]
 [    98.    162637.         0.835      0.679      7.        -5.329      0.         0.036      0.583      0.
       0.218      0.85     124.98       4.   ]]

  5 músicas menos populares:
[[     0.    176106.         0.618      0.334      2.  

#7) Produto Matricial

Normalize as colunas e mostre diagonal principal.

In [9]:
# Reutiliza dados_norm calculado no exercício 4
# Produto matricial: (14 x N) @ (N x 14) = (14 x 14)
produto = dados_norm.T @ dados_norm

# Diagonal principal: produto interno de cada feature consigo mesma
diagonal = np.diag(produto)

nomes_colunas = [
    "popularity", "duration_ms", "danceability", "energy", "key",
    "loudness", "mode", "speechiness", "acousticness",
    "instrumentalness", "liveness", "valence", "tempo", "time_signature"
]

np.set_printoptions(suppress=True, precision=2)

print("=== Produto Matricial: dados_norm.T @ dados_norm ===")
print(f"  Shape da matriz resultante: {produto.shape}")

print("\n  Diagonal principal (produto interno de cada feature consigo mesma):")
for nome, val in zip(nomes_colunas, diagonal):
    print(f"    {nome:<20}: {val:.2f}")

print("\n  Matriz completa (14 x 14):")
np.set_printoptions(suppress=True, precision=1, linewidth=120)
print(produto)

=== Produto Matricial: dados_norm.T @ dados_norm ===
  Shape da matriz resultante: (14, 14)

  Diagonal principal (produto interno de cada feature consigo mesma):
    popularity          : 17358.79
    duration_ms         : 246.08
    danceability        : 39027.21
    energy              : 51502.90
    key                 : 36200.60
    loudness            : 63726.71
    mode                : 67820.00
    speechiness         : 2098.01
    acousticness        : 21330.25
    instrumentalness    : 12289.97
    liveness            : 8291.93
    valence             : 31511.58
    tempo               : 28658.49
    time_signature      : 66056.88

  Matriz completa (14 x 14):
[[17358.8  1560.9 20836.4 23123.6 17305.6 27545.9 22591.1  3026.8 10928.2  4840.8  7281.2 16782.9 18056.7 28090.2]
 [ 1560.9   246.1  2668.9  3055.2  2261.2  3573.3  2921.2   395.1  1349.1   788.    956.1  2139.   2351.2  3646.1]
 [20836.4  2668.9 39027.2 40629.9 30127.  47813.2 38602.8  5655.8 17973.5  8337.3 12174.  3